#!/usr/bin/env -S node
/**
 * Emits a scorecard skeleton in the exact YAML shape
 * `docs/platform/library-rubric.md` section 9 defines, with `facts` filled in
 * from a candidate's measured `results/<lib>.json` (kind `npm` and context
 * `bundled` assumed — a research session overrides `kind`/`context` by hand
 * for a crate, image or SaaS candidate). `scores`, `extras`, `gates` and
 * `verdict` are left as the rubric's own placeholders: **this emitter never
 * scores anything** — scoring is judgement (`docs/platform/library-rubric.md`
 * section 2, "Scores are anchored, not vibes"), out of PAP-753's scope
 * (PAP-209 owns `pnpm lib score`).
 *
 * Usage: `tsx ../_kit/src/scorecard.ts <spikeDir> <candidateId> --issue PAP-n [--kind npm] [--context bundled] [--out path.yaml]`
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { stringify } from 'yaml';
import { subtractBaseline } from './bundle.ts';
import type { CandidateResult } from './schema.ts';

function flag(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}

const VALUE_FLAGS = new Set(['--issue', '--kind', '--context', '--out']);

function positionalArgs(argv: string[]): string[] {
  const positional: string[] = [];
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    if (VALUE_FLAGS.has(arg)) {
      i += 1; // skip this flag's value
      continue;
    }
    if (!arg.startsWith('--')) positional.push(arg);
  }
  return positional;
}

function main(): void {
  const argv = process.argv.slice(2);
  const [spikeDirArg, candidateId] = positionalArgs(argv);
  if (!spikeDirArg || !candidateId) {
    console.error('usage: scorecard.ts <spikeDir> <candidateId> --issue PAP-n [--kind npm] [--context bundled] [--out path]');
    process.exit(2);
  }
  const spikeDir = resolve(spikeDirArg);
  const issue = flag(argv, '--issue') ?? 'PAP-000';
  const kind = flag(argv, '--kind') ?? 'npm';
  const context = flag(argv, '--context') ?? 'bundled';

  const resultPath = join(spikeDir, 'results', `${candidateId}.json`);
  const result = JSON.parse(readFileSync(resultPath, 'utf8')) as CandidateResult;

  const gzipOwnBytes = subtractBaseline(result.bundle.gzipBytes, result.bundle.sharedBaselineGzipBytes);

  const scoreSkeleton = { score: null as number | null, evidence: `results/${candidateId}.json` };

  const scorecard = {
    candidate: result.lib,
    version: result.version,
    evaluatedBy: 'Scout',
    date: new Date().toISOString().slice(0, 10),
    issue,
    kind,
    context,
    facts: {
      gzipBytes: result.bundle.gzipBytes,
      gzipOwnBytes,
      wallTimeMeanMs: result.runtime.wallTimeMeanMs,
      wallTimeStable: result.runtime.stable,
      meanFps: result.browser.meanFps,
      p5Fps: result.browser.p5Fps,
      measuredFrom: `results/${candidateId}.json`,
    },
    scores: {
      license: { ...scoreSkeleton },
      maintenance: { ...scoreSkeleton },
      bundle: { ...scoreSkeleton },
      a11y: { ...scoreSkeleton },
      ts: { ...scoreSkeleton },
      agent: { ...scoreSkeleton },
    },
    extras: [] as unknown[],
    gates: {
      licenseTier: { result: 'pending', evidence: '' },
      noTypes: { result: 'pending', evidence: '' },
      webviewIncompatible: { result: 'pending', evidence: '' },
      vendorNoSelfHost: { result: 'pending', evidence: '' },
      openAdvisory: { result: 'pending', evidence: '' },
    },
    migrationCostHours: null as number | null,
    verdict: 'pending',
  };

  const rendered = `# Generated by spikes/_kit/src/scorecard.ts from ${resultPath}.\n# Fill scores/gates/verdict by hand per docs/platform/library-rubric.md, then\n# move this file to docs/libraries/scorecards/<candidate>@<version>.yaml.\n${stringify(scorecard)}`;

  const outPath = flag(argv, '--out');
  if (outPath) {
    mkdirSync(dirname(resolve(outPath)), { recursive: true });
    writeFileSync(resolve(outPath), rendered);
    console.log(`wrote ${outPath}`);
  } else {
    process.stdout.write(rendered);
  }
}

main();
