/**
 * JSON Schema generation (PAP-103). `pnpm --filter @paperos/agents gen:schemas` writes
 * `schema/character.schema.json` and `schema/roster.schema.json`; a test fails when the committed
 * copies drift. Editors pick the schema up from the `# yaml-language-server: $schema=` modeline at
 * the top of every character file.
 */
import { z } from 'zod';
import { CharacterSchema, RosterSchema, SCHEMA_VERSION } from './character.ts';

const BASE_ID = 'https://paperos.dev/schema/agents';

function generate(schema: z.ZodType, name: string): Record<string, unknown> {
  const json = z.toJSONSchema(schema, {
    target: 'draft-2020-12',
    io: 'input',
    unrepresentable: 'any',
  });
  const { $schema, ...rest } = json as Record<string, unknown>;
  return {
    $schema: $schema ?? 'https://json-schema.org/draft/2020-12/schema',
    $id: `${BASE_ID}/${name}.schema.json`,
    $comment: `Generated by \`pnpm --filter @paperos/agents gen:schemas\` from packages/agents/src/schema/character.ts (schemaVersion ${SCHEMA_VERSION}). Do not edit by hand.`,
    ...rest,
  };
}

export function characterJsonSchema(): Record<string, unknown> {
  return generate(CharacterSchema, 'character');
}

export function rosterJsonSchema(): Record<string, unknown> {
  return generate(RosterSchema, 'roster');
}

export function stringifySchema(schema: Record<string, unknown>): string {
  return `${JSON.stringify(schema, null, 2)}\n`;
}
