/**
 * The `audiences:` section of `app.spec.yaml` and its generated JSON Schema.
 *
 * ```yaml
 * audiences:
 *   vip:
 *     name: VIP customers
 *     description: Pro or enterprise customers with a partner id.
 *     match:
 *       all:
 *         - any: [{ audience: customer-pro }, { audience: customer-enterprise }]
 *         - { attr: partnerId, op: exists }
 * ```
 *
 * The JSON Schema is generated from the Zod schema (`pnpm --filter @paperos/core
 * gen:audience-schema`) into `audiences.schema.json`; never hand-edit that file.
 */
import { z } from 'zod';
import { audienceDeclarationSchema, audienceIdSchema } from './audience.js';

export const AUDIENCES_SCHEMA_ID = 'https://paperos.dev/schemas/app-spec/audiences.schema.json';

/** `Record<AudienceId, Omit<Audience, 'id'>>` — the shape PAP-117 embeds in `AppSpec`. */
export const audiencesSectionSchema = z.record(audienceIdSchema, audienceDeclarationSchema);

export type AudiencesSection = z.infer<typeof audiencesSectionSchema>;

/** JSON Schema (draft 2020-12) for the `audiences:` section. Deterministic: same input, same output. */
export function audiencesJsonSchema(): Record<string, unknown> {
  const generated = z.toJSONSchema(audiencesSectionSchema, {
    target: 'draft-2020-12',
    io: 'input',
    unrepresentable: 'any',
  });
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: AUDIENCES_SCHEMA_ID,
    $comment:
      'GENERATED by `pnpm --filter @paperos/core gen:audience-schema` from packages/core/src/audience/app-spec.ts. Do not edit; PAP-55, ADR 0017.',
    title: 'PaperOS app.spec.yaml audiences section',
    description:
      'Audiences an app declares on top of the built-ins: id (kebab-case segments joined by dots) to { name, description, match }. Built-in ids cannot be redeclared.',
    ...omit(generated, '$schema'),
  };
}

function omit<T extends Record<string, unknown>>(obj: T, key: string): Record<string, unknown> {
  const { [key]: _dropped, ...rest } = obj;
  return rest;
}
