#!/usr/bin/env node
/**
 * `pnpm --filter @paperos/agents gen:fixtures [--check]` (PAP-103).
 *
 * Resolves `fixtures/valid` (roster.yaml + characters/*.yaml) with inheritance applied and writes
 * the result to `fixtures/valid/roster.json`, the shape `agents.roster` (PAP-113) and the bundle
 * generator (PAP-106) consume. `--check` exits 1 on drift.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { readRosterDir, validateRosterFiles } from '../src/schema/load.ts';

const check = process.argv.includes('--check');
const root = resolve(new URL('..', import.meta.url).pathname, 'fixtures/valid');
const result = validateRosterFiles(readRosterDir(root));
if (!result.ok || !result.roster) {
  for (const f of result.errors) console.error(`${f.code} ${f.character ?? ''} ${f.message}`);
  process.exit(1);
}
const { characters, ...rest } = result.roster;
const sorted = [...characters].sort((a, b) =>
  a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind === 'lead' ? -1 : 1,
);
const text = `${JSON.stringify(
  {
    $comment:
      'Generated by `pnpm --filter @paperos/agents gen:fixtures` from fixtures/valid/roster.yaml and characters/*.yaml with inheritance resolved. Do not edit by hand.',
    ...rest,
    characters: sorted,
  },
  null,
  2,
)}\n`;
const out = resolve(root, 'roster.json');
const current = existsSync(out) ? readFileSync(out, 'utf8') : undefined;
if (check) {
  if (current !== text) {
    console.error('gen:fixtures --check: fixtures/valid/roster.json is stale');
    process.exit(1);
  }
  console.log('fixtures/valid/roster.json up to date');
} else {
  writeFileSync(out, text);
  console.log(`wrote fixtures/valid/roster.json (${sorted.length} characters)`);
}
