/**
 * JSON Schema generation. Pure: the `gen:schemas` script writes these to `schema/`, the drift
 * test regenerates them and compares. Generated with `io: 'input'` because the files describe
 * what may be written (`page.spec.yaml` inline views, PAP-119; the API), where defaults are
 * optional. Refinements (duplicate ids, computed rule, public-needs-sharing) are not expressible
 * in JSON Schema and are documented as "Zod only" in docs/platform/view-model.md.
 */
import { z } from 'zod';
import { datasetRefSchema } from './dataset-ref.js';
import { fieldDefSchema } from './field.js';
import { VIEW_SPEC_VERSION, viewSpecSchema } from './view.js';

export const SCHEMA_ID_BASE = 'https://paperos.dev/schema';

export type JsonSchema = Record<string, unknown>;

function generate(schema: z.ZodType, id: string, title: string, description: string): JsonSchema {
  const json = z.toJSONSchema(schema, {
    target: 'draft-2020-12',
    io: 'input',
    unrepresentable: 'any',
    // Named sub-schemas (`.meta({ id })`) become `$defs`; everything else is inlined for readability.
    reused: 'inline',
  }) as JsonSchema;
  return { $schema: json.$schema, $id: id, title, description, ...withoutSchemaKey(json) };
}

function withoutSchemaKey(json: JsonSchema): JsonSchema {
  const { $schema: _dropped, ...rest } = json;
  return rest;
}

export function buildViewSpecJsonSchema(): JsonSchema {
  return generate(
    viewSpecSchema,
    `${SCHEMA_ID_BASE}/view/${VIEW_SPEC_VERSION}`,
    'ViewSpec',
    'PaperOS view specification (PAP-161, ADR 0016). Generated by `pnpm --filter @paperos/views gen:schemas`; do not edit.',
  );
}

export function buildFieldDefJsonSchema(): JsonSchema {
  return generate(
    fieldDefSchema,
    `${SCHEMA_ID_BASE}/field-def/1`,
    'FieldDef',
    'PaperOS dataset field definition (PAP-161, ADR 0016). Generated by `pnpm --filter @paperos/views gen:schemas`; do not edit.',
  );
}

export function buildDatasetRefJsonSchema(): JsonSchema {
  return generate(
    datasetRefSchema,
    `${SCHEMA_ID_BASE}/dataset-ref/1`,
    'DatasetRef',
    'PaperOS dataset reference: `{ kind: "entity", key }` or `{ kind: "custom", datasetId }` (PAP-161). Generated; do not edit.',
  );
}

/** File name to builder; the script and the drift test iterate this. */
export const GENERATED_SCHEMAS: Readonly<Record<string, () => JsonSchema>> = {
  'view.schema.json': buildViewSpecJsonSchema,
  'field-def.schema.json': buildFieldDefJsonSchema,
  'dataset-ref.schema.json': buildDatasetRefJsonSchema,
};
