#!/usr/bin/env node
/**
 * Generate THIRD_PARTY_NOTICES.md from the licence report (PAP-211, ADR 0027).
 *
 *   node ops/licenses/notices.mjs                 # write THIRD_PARTY_NOTICES.md
 *   node ops/licenses/notices.mjs --check         # fail if the committed file is stale
 *   node ops/licenses/notices.mjs --out <path>
 *
 * Attribution is owed for what we SHIP, so the notices come from the report's
 * `notices` list: the production closure (contexts `bundled`, `server` and
 * `service`), never the dev toolchain. `--check` is what CI runs, so a new
 * production dependency cannot land without its attribution.
 *
 * Exit codes: 0 written or up to date, 1 stale under `--check`, 2 could not run.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const HERE = import.meta.dirname;
const DEFAULT_ROOT = resolve(HERE, '..', '..');
const HEADER = '<!-- Generated by ops/licenses/notices.mjs (PAP-211). Do not edit by hand. -->';

export function renderNotices(report, { repository = 'paperos-template' } = {}) {
  const lines = [];
  lines.push(HEADER);
  lines.push('');
  lines.push('# Third-party notices');
  lines.push('');
  lines.push(
    `\`${repository}\` ships the open-source packages below. Each is used under the licence named`,
  );
  lines.push(
    'beside it; the full texts are in the packages themselves under `node_modules/<name>/LICENSE`.',
  );
  lines.push('');
  lines.push('Regenerate with `node ops/licenses/notices.mjs`; the list comes from the production');
  lines.push('dependency closure in `reports/licenses.json` (policy: `ops/licenses/policy.yaml`).');
  lines.push('');
  const byLicense = new Map();
  for (const entry of report.notices ?? []) {
    if (!byLicense.has(entry.license)) byLicense.set(entry.license, []);
    byLicense.get(entry.license).push(entry);
  }
  if (byLicense.size === 0) {
    lines.push('No third-party production dependencies are bundled today.');
    lines.push('');
    return `${lines.join('\n')}`;
  }
  for (const license of [...byLicense.keys()].sort()) {
    lines.push(`## ${license}`);
    lines.push('');
    lines.push('| Package | Version | Context | Home |');
    lines.push('| -- | -- | -- | -- |');
    for (const entry of byLicense.get(license).sort((a, b) => a.package.localeCompare(b.package))) {
      lines.push(
        `| \`${entry.package}\` | ${entry.version} | ${entry.context} | ${entry.homepage ? `<${entry.homepage}>` : '—'} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function run(argv, { log = console.log, error = console.error } = {}) {
  let root = DEFAULT_ROOT;
  let reportPath = null;
  let out = 'THIRD_PARTY_NOTICES.md';
  let check = false;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const value = () => {
      i += 1;
      return argv[i];
    };
    if (arg === '--check') check = true;
    else if (arg === '--root') root = resolve(value());
    else if (arg === '--report') reportPath = value();
    else if (arg === '--out') out = value();
    else {
      error(`unknown option ${arg}`);
      return 2;
    }
  }
  const report = resolve(root, reportPath ?? 'reports/licenses.json');
  if (!existsSync(report)) {
    error(`no licence report at ${report} — run \`node ops/licenses/check.mjs\` first`);
    return 2;
  }
  const rendered = `${renderNotices(JSON.parse(readFileSync(report, 'utf8')))}\n`.replace(
    /\n{3,}$/,
    '\n',
  );
  const target = resolve(root, out);
  if (check) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== rendered) {
      error(`${out} is stale — run \`node ops/licenses/notices.mjs\``);
      return 1;
    }
    log(`${out} is up to date`);
    return 0;
  }
  writeFileSync(target, rendered);
  log(`wrote ${target}`);
  return 0;
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === resolve(HERE, 'notices.mjs');
if (invokedDirectly) process.exit(run(process.argv.slice(2)));
