/**
 * The PaperOS domain event envelope — Interface & Data Contracts section 3, verbatim.
 *
 * Every producer publishes this shape and every subscriber receives it, whether the event came
 * from a router, an audit trigger, a job or an external webhook receiver normalising a Stripe or
 * Linear payload (`actor.type = 'service'`).
 */
import { z } from 'zod';
import { actorRefSchema, entityRefSchema, isoDateTimeSchema, uuidSchema } from './refs.js';

/** `<entity>.<past-tense-verb>[.<qualifier>]`, lower-case, dot-separated, at most 48 characters. */
export const TOPIC_NAME_PATTERN = /^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9_]*){1,3}$/;
export const TOPIC_NAME_MAX_LENGTH = 48;

export const topicNameSchema = z
  .string()
  .max(TOPIC_NAME_MAX_LENGTH, `topic names are at most ${TOPIC_NAME_MAX_LENGTH} characters`)
  .regex(
    TOPIC_NAME_PATTERN,
    "topic names are lower-case '<entity>.<past-tense-verb>[.<qualifier>]'",
  );

/** Why a topic name was rejected, or `undefined` when it is well formed. */
export function topicNameProblem(name: string): string | undefined {
  if (name.length > TOPIC_NAME_MAX_LENGTH) {
    return `topic '${name}' is ${name.length} characters, the limit is ${TOPIC_NAME_MAX_LENGTH}`;
  }
  if (!TOPIC_NAME_PATTERN.test(name)) {
    return `topic '${name}' does not match '<entity>.<past-tense-verb>[.<qualifier>]' (lower-case, dot-separated, 2 to 4 segments)`;
  }
  return undefined;
}

/**
 * The envelope. `payload` is `unknown` here and narrowed by the topic registry: the typed view is
 * `DomainEvent<TopicPayload<'invoice.paid'>>`.
 */
export const domainEventSchema = z.object({
  /** UUIDv7, generated by the publisher; subscribers are idempotent on it. */
  id: uuidSchema,
  topic: topicNameSchema,
  /** Bumped on a breaking payload change; readers for the previous version live 30 days. */
  version: z.number().int().positive(),
  /** Database `now()` at insert, never the process clock (clock skew between API instances). */
  occurredAt: isoDateTimeSchema,
  /** `null` for platform-level events that belong to no tenant. */
  tenantId: uuidSchema.nullable(),
  actor: actorRefSchema,
  subject: entityRefSchema,
  requestId: z.string().min(1).max(128).optional(),
  causationId: uuidSchema.optional(),
  correlationId: uuidSchema.optional(),
  idempotencyKey: z.string().min(1).max(255).optional(),
  payload: z.unknown(),
});

type EnvelopeFields = Omit<z.infer<typeof domainEventSchema>, 'payload'>;

/** A published event. `P` is the topic's payload type. */
export type DomainEvent<P = unknown> = EnvelopeFields & { readonly payload: P };

/** What a producer hands `publish()`: no `id` and no `occurredAt`, both assigned on insert. */
export interface PublishInputBase {
  /** `null` for platform events; required on every tenant-scoped topic. */
  readonly tenantId: string | null;
  readonly actor: z.infer<typeof actorRefSchema>;
  readonly subject: z.infer<typeof entityRefSchema>;
  /** Defaults to the registered topic version. */
  readonly version?: number;
  readonly requestId?: string;
  readonly causationId?: string;
  readonly correlationId?: string;
  /** Second publish of the same key in the same tenant is a no-op. */
  readonly idempotencyKey?: string;
  /** Supply an id only in tests or when replaying a recorded event. */
  readonly id?: string;
}

export const publishInputBaseSchema = domainEventSchema
  .omit({ id: true, occurredAt: true, topic: true, payload: true, version: true })
  .extend({
    version: z.number().int().positive().optional(),
    id: uuidSchema.optional(),
  });
