/**
 * Renders `docs/platform/page-spec.md` from the generated JSON Schema and the
 * issue-code registry. Generated, never hand-edited; the drift test guards it.
 */
import { SPEC_CODES } from './issues.js';
import type { JsonSchema } from './json-schema.js';

interface Row {
  path: string;
  type: string;
  required: boolean;
  description: string;
}

const GENERATED_NOTICE =
  '<!-- GENERATED by `pnpm --filter @paperos/spec gen:schemas` from packages/spec/src/schema/*.ts. Do not edit; change the Zod schema or `src/docs.ts` and regenerate. -->';

export function renderPageSpecDoc(schema: JsonSchema): string {
  const defs = (schema.$defs ?? {}) as Record<string, JsonSchema>;
  const lines: string[] = [];
  const push = (...text: string[]): void => {
    lines.push(...text);
  };

  push(
    GENERATED_NOTICE,
    '',
    '# Page spec reference (`page.spec.yaml` v1)',
    '',
    'Every PaperOS page is a file `specs/pages/<id>.spec.yaml` validated by `@paperos/spec`',
    '(`parseSpec`, `validatePageSpec`) against `PageSpecSchema` (Zod 4). The JSON Schema for editors is',
    '[`packages/spec/schema/page.spec.schema.json`](../../packages/spec/schema/page.spec.schema.json);',
    'the first line of every spec points at it:',
    '',
    '```yaml',
    '# yaml-language-server: $schema=../../packages/spec/schema/page.spec.schema.json',
    '```',
    '',
    'Decision record: [ADR 0015](../adr/0015-page-spec-schema.md). Examples: [`specs/pages/`](../../specs/pages/).',
    '',
    '## Rules the schema cannot say on its own',
    '',
    '* `meta.id` equals the file name stem (`customer-invoices.spec.yaml` → `customer-invoices`).',
    '* `meta.specVersion` missing is read as `1` with `SPEC_VERSION_MISSING`; any other value is `SPEC_UNSUPPORTED_VERSION`.',
    '* Unknown top-level keys are errors unless prefixed `x-` (`x-*` passes through untouched). The v1.1 keys',
    `  ${(schema['x-paperos'] as { reservedKeys: string[] }).reservedKeys.map((k) => `\`${k}\``).join(', ')} parse as unknown with \`SPEC_RESERVED_KEY\` (PAP-740).`,
    '* Nested unknown keys are errors everywhere; the hint names the closest allowed key.',
    '* Every `components[].events` value, `states.*.action`, `edgeCases[].action`, `access.actions` key and',
    '  action-sourced `events[].on` must be a key under `logic.actions` (`SPEC_ACTION_UNBOUND`).',
    '* `components[].key` and `edgeCases[].id` are page-unique; duplicates list both lines.',
    '* `events[].to` is a `$param` route, or an http(s) URL when `kind: external`.',
    '* User-visible text (`meta.title`, `states.*.copy`, `logic.actions.*.intent`, notification copy) is a message',
    '  catalog key or `{ id, default }`, never a literal sentence (`SPEC_LITERAL_COPY`). Keys are',
    '  `<specId>.<path>`; the English text lives in `default` and seeds the catalog (PAP-375).',
    '* YAML anchors and merge keys are resolved before validation; positions point at the merged document.',
    '* Duplicate YAML keys are errors (`SPEC_DUP_KEY`) with both lines; BOM and CRLF are normalised.',
    '* Specs over 200 KB warn (`SPEC_TOO_LARGE`).',
    '',
    '### `status: ready` gate',
    '',
    'A page may move from `draft` to `ready` only when all of these hold (`SPEC_READY_INCOMPLETE` otherwise):',
    '',
    '1. `access` is present.',
    '2. `data` is present, or the page is marked `x-static: true`.',
    '3. At least three `edgeCases`.',
    '4. Every `events[].to` resolves to a declared route (checked when the validator is given `knownRoutes`; PAP-115 supplies them).',
    '',
    'Warnings on a `ready` page: a missing standard state (`SPEC_READY_STATES`: `error` and `denied` always, `loading`',
    'and `empty` with `data`, `offline` with `live` or `local` queries). A `built` page with `not-wired` components or',
    'actions warns `SPEC_BUILT_NOT_WIRED`.',
    '',
    '### Actions registry, placeholders and languages',
    '',
    "* `logic.actions` is the page's actions registry: each entry has an `intent` phrase (message key, so it exists in",
    '  English and Spanish), a `permission` and `steps`. `pageActions(spec)` flattens it for the WebMCP surface and the',
    '  voice controller; component `events` bind to these ids.',
    '* `status: not-wired` on a component or action marks a placeholder: dev mode shows it and activation shows the',
    '  "not wired yet" toast. `notWiredComponents(spec)` lists them.',
    '',
    '## Sections',
    '',
    '| Path | Type | Required | Description |',
    '| -- | -- | -- | -- |',
  );

  for (const row of rowsOf(schema, '', defs, true)) {
    push(
      `| \`${row.path}\` | ${row.type} | ${row.required ? 'yes' : 'no'} | ${escapeCell(row.description)} |`,
    );
  }

  push('', '## Types', '', 'Named shapes referenced above (`$defs` in the JSON Schema).', '');

  for (const [name, def] of Object.entries(defs)) {
    push(`### ${name}`, '');
    if (typeof def.description === 'string') push(def.description, '');
    if (typeof def.pattern === 'string') {
      push('```regex', def.pattern, '```', '');
    } else if (Array.isArray(def.enum)) {
      push(`One of: ${def.enum.map((v) => `\`${String(v)}\``).join(', ')}.`, '');
    } else if (def.type === 'object' || def.anyOf || def.type === 'array') {
      const rows = rowsOf(def, '', defs, false);
      if (rows.length > 0) {
        push('| Path | Type | Required | Description |', '| -- | -- | -- | -- |');
        for (const row of rows) {
          push(
            `| \`${row.path}\` | ${row.type} | ${row.required ? 'yes' : 'no'} | ${escapeCell(row.description)} |`,
          );
        }
        push('');
      }
    }
  }

  push(
    '## Issue codes',
    '',
    'Every issue `parseSpec` / `validatePageSpec` can raise. `hint` says what to do.',
    '',
  );
  push('| Code | Severity | Meaning |', '| -- | -- | -- |');
  for (const [code, info] of Object.entries(SPEC_CODES)) {
    push(`| \`${code}\` | ${info.severity} | ${escapeCell(info.summary)} |`);
  }
  push('');
  return `${lines.join('\n')}`;
}

function rowsOf(
  schema: JsonSchema,
  prefix: string,
  defs: Record<string, JsonSchema>,
  recurseInline: boolean,
): Row[] {
  const rows: Row[] = [];
  const node = resolveInline(schema, defs);
  const properties = (node.properties ?? {}) as Record<string, JsonSchema>;
  const required = new Set((node.required as string[] | undefined) ?? []);
  for (const [key, value] of Object.entries(properties)) {
    const path = prefix ? `${prefix}.${key}` : key;
    const description = String(value.description ?? refDescription(value, defs) ?? '');
    rows.push({
      path,
      type: typeOf(value, defs),
      required: required.has(key),
      description: withDefault(description, value),
    });
    if (recurseInline && !value.$ref && value.type === 'object' && value.properties) {
      rows.push(...rowsOf(value, path, defs, recurseInline));
    }
  }
  if (node.type === 'array' && node.items) {
    const items = node.items as JsonSchema;
    const path = `${prefix}[]`;
    rows.push({
      path,
      type: typeOf(items, defs),
      required: false,
      description: String(items.description ?? ''),
    });
  }
  return rows;
}

function resolveInline(schema: JsonSchema, defs: Record<string, JsonSchema>): JsonSchema {
  if (typeof schema.$ref === 'string') {
    const name = schema.$ref.replace('#/$defs/', '');
    return defs[name] ?? schema;
  }
  return schema;
}

function refDescription(schema: JsonSchema, defs: Record<string, JsonSchema>): string | undefined {
  const resolved = resolveInline(schema, defs);
  return typeof resolved.description === 'string' ? resolved.description : undefined;
}

function withDefault(description: string, schema: JsonSchema): string {
  if (!('default' in schema)) return description;
  const value = JSON.stringify(schema.default);
  const short = value.length > 30 ? `${value.slice(0, 27)}...` : value;
  return `${description} Default \`${short}\`.`.trim();
}

function typeOf(schema: JsonSchema, defs: Record<string, JsonSchema>): string {
  if (typeof schema.$ref === 'string') {
    const name = schema.$ref.replace('#/$defs/', '');
    return `[${name}](#${name.toLowerCase()})`;
  }
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => `\`${String(v)}\``).join(' \\| ');
  if (Array.isArray(schema.anyOf))
    return (schema.anyOf as JsonSchema[]).map((s) => typeOf(s, defs)).join(' \\| ');
  if ('const' in schema) return `\`${JSON.stringify(schema.const)}\``;
  if (schema.type === 'array' && schema.items)
    return `${typeOf(schema.items as JsonSchema, defs)}[]`;
  if (schema.type === 'object') {
    const value = schema.additionalProperties;
    if (value && typeof value === 'object' && !schema.properties) {
      const key = (schema.propertyNames as JsonSchema | undefined) ?? {};
      return `record<${typeOf(key, defs) === 'unknown' ? 'string' : typeOf(key, defs)}, ${typeOf(value as JsonSchema, defs)}>`;
    }
    return 'object';
  }
  if (typeof schema.type === 'string') return schema.type;
  if (Array.isArray(schema.type)) return schema.type.join(' \\| ');
  return 'unknown';
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
