import { describe, expect, it } from 'vitest';
import { renderNotices } from '../notices.mjs';

describe('renderNotices', () => {
  const report = {
    notices: [
      {
        package: 'react',
        version: '19.3.0',
        license: 'MIT',
        context: 'bundled',
        homepage: 'https://react.dev/',
      },
      {
        package: 'drizzle-orm',
        version: '0.45.2',
        license: 'Apache-2.0',
        context: 'bundled',
        homepage: null,
      },
      {
        package: 'zod',
        version: '4.6.5',
        license: 'MIT',
        context: 'bundled',
        homepage: 'https://zod.dev',
      },
    ],
  };

  it('groups by licence and sorts inside each group', () => {
    const rendered = renderNotices(report);
    expect(rendered).toMatch(/Generated by ops\/licenses\/notices\.mjs/);
    expect(rendered.indexOf('## Apache-2.0')).toBeLessThan(rendered.indexOf('## MIT'));
    expect(rendered.indexOf('`react`')).toBeLessThan(rendered.indexOf('`zod`'));
    expect(rendered).toMatch(/\| `drizzle-orm` \| 0\.45\.2 \| bundled \| — \|/);
  });

  it('says so plainly when nothing is bundled', () => {
    expect(renderNotices({ notices: [] })).toMatch(
      /No third-party production dependencies are bundled today\./,
    );
  });
});
