/**
 * Render `docs/platform/events.md` from the topic registry.
 *
 *   pnpm --filter @paperos/core run events:catalogue            # write
 *   pnpm --filter @paperos/core run events:catalogue -- --check # fail on drift (Gate 1)
 *
 * The doc is **generated, never hand-edited** (CLAUDE.md, "Never edit generated files"). Because
 * every row carries the payload's JSON Schema fingerprint, a payload changed without a `version`
 * bump shows up as drift here and fails the gate — which is the point.
 *
 * Imports are relative on purpose: this file sits above the workspace packages, so it resolves
 * `@paperos/core` through the source tree rather than through a package alias.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { TopicDefinition } from '../packages/core/src/events/index.js';
import { topics } from '../packages/core/src/events/index.js';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const outputPath = join(repoRoot, 'docs/platform/events.md');

interface JsonSchemaLike {
  readonly type?: unknown;
  readonly properties?: Record<string, JsonSchemaLike>;
  readonly required?: string[];
  readonly enum?: unknown[];
  readonly anyOf?: JsonSchemaLike[];
  readonly items?: JsonSchemaLike;
  readonly format?: string;
  readonly pattern?: string;
}

function typeOf(schema: JsonSchemaLike): string {
  if (Array.isArray(schema.enum)) return schema.enum.map((v) => `\`${String(v)}\``).join(' \\| ');
  if (Array.isArray(schema.anyOf)) return schema.anyOf.map(typeOf).join(' \\| ');
  if (schema.type === 'array')
    return `${schema.items === undefined ? 'unknown' : typeOf(schema.items)}[]`;
  if (schema.type === 'null') return 'null';
  if (typeof schema.type === 'string') {
    if (schema.format !== undefined) return `${schema.type} (${schema.format})`;
    return schema.type;
  }
  return 'unknown';
}

function payloadRows(topic: TopicDefinition): string {
  const schema = topic.jsonSchema as JsonSchemaLike;
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const entries = Object.entries(properties);
  if (entries.length === 0) return '_No payload fields._\n';
  const rows = entries.map(
    ([name, field]) => `| \`${name}\` | ${typeOf(field)} | ${required.has(name) ? 'yes' : 'no'} |`,
  );
  return ['| Field | Type | Required |', '| -- | -- | -- |', ...rows].join('\n');
}

function render(all: readonly TopicDefinition[]): string {
  const header = [
    '<!-- Generated by scripts/events-catalogue.ts. Do not edit by hand: run',
    '     `pnpm --filter @paperos/core run events:catalogue`. CI runs it with `--check`. -->',
    '',
    '# Event catalogue',
    '',
    'Every topic registered with `defineTopic()` in `@paperos/core/events`. The envelope, the',
    'transactional outbox and the delivery rules are [ADR 0013](../adr/0013-domain-events-outbox.md);',
    'the shapes are Interface & Data Contracts section 3.',
    '',
    `${all.length} topics. Producers marked **placeholder** are registered here so consumers can`,
    'subscribe today; the owning issue flips the status to `live` in the commit that starts',
    'publishing.',
    '',
    '## Rules a subscriber can rely on',
    '',
    '* Delivery is **at-least-once**, so every handler is idempotent on `event.id` and says so',
    '  (`on(topic, handler, { name, idempotent: true })`).',
    '* Ordering is guaranteed **per `subject`** only, never across subjects.',
    '* `occurredAt` is the database `now()` at insert, never a process clock.',
    '* Payloads carry **ids and changed fields only** — no rows, no names, no contact details. The',
    '  PII denylist (`packages/core/src/events/pii.json`) is enforced when the topic is registered',
    '  and again when an event is published; payloads over 64 KB are rejected.',
    '* A breaking payload change bumps `version`; the previous reader lives 30 days.',
    '',
    '## Topics',
    '',
    '| Topic | v | Status | Producer | What it means |',
    '| -- | -- | -- | -- | -- |',
    ...all.map(
      (topic) =>
        `| [\`${topic.name}\`](#${topic.name.replace(/\./g, '')}) | ${topic.version} | ${topic.status} | ${topic.producer} | ${topic.description} |`,
    ),
    '',
    '## Payloads',
    '',
  ];

  const sections = all.flatMap((topic) => [
    `### ${topic.name}`,
    '',
    topic.description,
    '',
    `* Version \`${topic.version}\` · status \`${topic.status}\` · schema \`${topic.schemaHash}\``,
    `* Producer: ${topic.producer}`,
    `* Known consumers: ${topic.consumers.length === 0 ? '—' : topic.consumers.join(', ')}`,
    '',
    payloadRows(topic),
    '',
  ]);

  return `${[...header, ...sections].join('\n').trimEnd()}\n`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const rendered = render(topics());

  if (!check) {
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, rendered, 'utf8');
    process.stdout.write(
      `events:catalogue wrote ${topics().length} topics to docs/platform/events.md\n`,
    );
    return;
  }

  let current = '';
  try {
    current = readFileSync(outputPath, 'utf8');
  } catch {
    process.stderr.write(
      'events:catalogue --check: docs/platform/events.md is missing. Run `pnpm --filter @paperos/core run events:catalogue`.\n',
    );
    process.exit(1);
  }

  if (current === rendered) {
    process.stdout.write(
      `events:catalogue --check: docs/platform/events.md is current (${topics().length} topics)\n`,
    );
    return;
  }

  const currentLines = current.split('\n');
  const renderedLines = rendered.split('\n');
  const firstDiff = renderedLines.findIndex((line, index) => line !== currentLines[index]);
  process.stderr.write(
    [
      'events:catalogue --check: docs/platform/events.md is out of date.',
      `  first difference at line ${firstDiff + 1}`,
      `  committed: ${currentLines[firstDiff] ?? '<end of file>'}`,
      `  generated: ${renderedLines[firstDiff] ?? '<end of file>'}`,
      '  fix: pnpm --filter @paperos/core run events:catalogue',
      '  a changed payload schema also needs a version bump (Contracts section 3).',
      '',
    ].join('\n'),
  );
  process.exit(1);
}

main();
